#!/bin/bash
#
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

if [ -d "venvp3" ]; then
  source venvp3/bin/activate
fi

echo "[$(date)] ==================== Cleaning up resources... ===================="
# [START hypercomputer_tpu_tune_qwen3_30b_rl_cleanup]

# Strip random hex suffix to get base pattern
BASE_CLUSTER_NAME=$(echo "${CLUSTER_NAME}" | sed -E 's/-[a-f0-9]{4}$//')

# 1. Discover ALL clusters generated by this run (including retry attempts)
CLUSTERS_TO_DELETE=()
while IFS= read -r line; do
  [ -n "$line" ] && CLUSTERS_TO_DELETE+=("$line")
done < <(gcloud container clusters list --project="${PROJECT}" --location="${REGION}" --filter="name~'^${BASE_CLUSTER_NAME}'" --format="value(name)" 2>/dev/null || true)

if [ ${#CLUSTERS_TO_DELETE[@]} -gt 0 ]; then
  for TARGET_CLUSTER in "${CLUSTERS_TO_DELETE[@]}"; do
    echo "Processing teardown for cluster: ${TARGET_CLUSTER}..."

    # 1a. Delete active workloads and JobSets if cluster endpoint is responsive
    xpk workload delete --workload "qwen-hf-to-mt" --cluster "${TARGET_CLUSTER}" --project="${PROJECT}" --zone="${ZONE}" 2>/dev/null || true
    xpk workload delete --workload "qwen-training" --cluster "${TARGET_CLUSTER}" --project="${PROJECT}" --zone="${ZONE}" 2>/dev/null || true
    xpk workload delete --workload "qwen-mt-to-hf" --cluster "${TARGET_CLUSTER}" --project="${PROJECT}" --zone="${ZONE}" 2>/dev/null || true

    # 1b. Wait for any running cluster operations to finish (prevents error 400/RESOURCE_IN_USE)
    echo "Checking for in-flight operations on ${TARGET_CLUSTER}..."
    RUNNING_OPS=$(gcloud container operations list --project="${PROJECT}" --location="${REGION}" --filter="targetLink~'${TARGET_CLUSTER}' AND status=RUNNING" --format="value(name)" 2>/dev/null || true)
    for op in $RUNNING_OPS; do
      if [ -n "$op" ]; then
        echo "Waiting for operation $op to finish before deletion..."
        gcloud container operations wait "$op" --project="${PROJECT}" --location="${REGION}" --timeout=120 2>/dev/null || true
      fi
    done

    # 1c. Robust deletion with retry loop (tries xpk, falls back to direct gcloud cluster delete)
    echo "Deleting GKE cluster ${TARGET_CLUSTER}..."
    DELETE_SUCCESS=false
    for attempt in {1..5}; do
      echo "Deletion attempt $attempt/5 for ${TARGET_CLUSTER}..."

      # Xpk cluster delete
      if xpk cluster delete --cluster "${TARGET_CLUSTER}" --project "${PROJECT}" --zone "${ZONE}" --force 2>/dev/null; then
        DELETE_SUCCESS=true
        break
      fi

      # Fallback to direct synchronous gcloud delete
      if gcloud container clusters delete "${TARGET_CLUSTER}" --location="${REGION}" --project="${PROJECT}" --quiet 2>/dev/null; then
        DELETE_SUCCESS=true
        break
      fi

      echo "Cluster delete rejected (likely pending reconciliation). Waiting 20s before retry..."
      sleep 20
    done

    if [ "$DELETE_SUCCESS" = false ]; then
      echo "Warning: Direct cluster deletion timed out; continuing with resource sweep..."
    fi
  done
else
  echo "No active GKE clusters found matching ${BASE_CLUSTER_NAME}."
fi

# 2. Terminate residual orphan VM instances strictly bound to this run
echo "Terminating residual VM instances attached to ${BASE_CLUSTER_NAME}..."
gcloud compute instances list \
  --project="${PROJECT}" \
  --zones="${ZONE}" \
  --filter="(labels.goog-k8s-cluster-name~'^${BASE_CLUSTER_NAME}' OR name~'^gke-${BASE_CLUSTER_NAME}')" \
  --format="value(name,zone.basename())" 2>/dev/null | while read -r name zone; do
    if [ -n "$name" ] && [ -n "$zone" ]; then
      echo " -> Deleting orphan instance: $name ($zone)"
      gcloud compute instances delete "$name" --zone="$zone" --project="${PROJECT}" --quiet 2>/dev/null || true
    fi
done

# 2b. Clean up any residual managed instance groups left behind by failed node-pools
gcloud compute instance-groups managed list \
  --project="${PROJECT}" \
  --filter="name~'${BASE_CLUSTER_NAME}'" \
  --format="value(name,zone.basename())" 2>/dev/null | while read -r igm_name igm_zone; do
    if [ -n "$igm_name" ] && [ -n "$igm_zone" ]; then
      echo " -> Deleting residual IGM: $igm_name in $igm_zone"
      gcloud compute instance-groups managed delete "$igm_name" --zone="$igm_zone" --project="${PROJECT}" --quiet 2>/dev/null || true
    fi
done

# 3. Clean up Pathways ANP networking stack (Firewalls -> Subnets -> VPCs)
RUN_HASH=$(echo "${BASE_CLUSTER_NAME}" | sed -E 's/pkb-//; s/-cluster//')

if [ -n "$RUN_HASH" ]; then
  echo "Cleaning up ANP networking stack for run hash: ${RUN_HASH}..."

  # 3a. Delete firewall rules
  gcloud compute firewall-rules list \
    --project="${PROJECT}" \
    --filter="network~'gke-anp.*${RUN_HASH}'" \
    --format="value(name)" 2>/dev/null | while read -r fw; do
      [ -n "$fw" ] && gcloud compute firewall-rules delete "$fw" --project="${PROJECT}" --quiet 2>/dev/null || true
  done

  # 3b. Delete subnetworks
  gcloud compute networks subnets list \
    --project="${PROJECT}" \
    --filter="name~'gke-anp.*${RUN_HASH}'" \
    --format="value(name,region.basename())" 2>/dev/null | while read -r subnet sub_region; do
      if [ -n "$subnet" ]; then
        gcloud compute networks subnets delete "$subnet" --region="${sub_region:-$REGION}" --project="${PROJECT}" --quiet 2>/dev/null || true
      fi
  done

  # 3c. Delete VPC networks
  gcloud compute networks list \
    --project="${PROJECT}" \
    --filter="name~'gke-anp.*${RUN_HASH}'" \
    --format="value(name)" 2>/dev/null | while read -r net; do
      [ -n "$net" ] && gcloud compute networks delete "$net" --project="${PROJECT}" --quiet 2>/dev/null || true
  done
fi

# 4. Wait until TPU reservation is confirmed 100% free
if [ -n "${RESERVATION:-}" ]; then
  echo "Verifying TPU reservation ${RESERVATION} release..."
  for i in {1..18}; do
    IN_USE=$(gcloud beta compute reservations describe "${RESERVATION}" \
      --project="${PROJECT}" \
      --zone="${ZONE}" \
      --format="value(specificReservation.inUseCount)" 2>/dev/null || echo "0")

    if [ -z "$IN_USE" ] || [ "$IN_USE" -eq 0 ]; then
      echo "TPU reservation ${RESERVATION} is completely free (0 chips in use)."
      break
    fi
    echo "TPU chips still in use: ${IN_USE}. Waiting 10s ($i/18)..."
    sleep 10
  done
fi

# 5. Clean up only run-specific model artifacts from Cloud Storage (keeps bucket & shared container image intact)
echo "Cleaning up run artifacts from Cloud Storage..."
if [ -n "${GCS_BUCKET:-}" ] && [ -n "${MODEL_NAME:-}" ]; then
  gcloud storage rm --recursive "gs://${GCS_BUCKET}/${MODEL_NAME}/" 2>/dev/null || echo "Info: No artifacts found under gs://${GCS_BUCKET}/${MODEL_NAME}/"
fi

# [END hypercomputer_tpu_tune_qwen3_30b_rl_cleanup]
echo "[$(date)] ==================== Resources cleaned up. ===================="
